server:
  name: "video_server"
  addr: "127.0.0.1:8080"
zap:
  debugFileName: ""
  infoFileName: ""
  warnFileName: ""
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "192.168.132.1"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8888"
  name: "video_server"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: zcm
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: douyin
oss:
  endpoint: "oss-cn-beijing.aliyuncs.com"
  accessKeyId: "LTAI5tPFHQ8m9BsPdFjqYaaM"
  accessKeySecret: "eGBrsinHT3NfsnZc6SBbzT8n5hMeSl"
  bucketName: "zcmvideos"
  codedir: "codedir/"
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: video_server
  refreshSecret: video_server
