// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "userServer"

// User mapped from table <userServer>
type User struct {
	UserID     int64     `gorm:"column:user_id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"user_id"`        // 主键
	Username   string    `gorm:"column:username;type:varchar(32);not null" json:"username"`                               // 用户名
	Password   string    `gorm:"column:password;type:varchar(32)" json:"password"`                                        // 密码
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
